spring:
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    username: ogulcan
    password: 1234ogul
    url: jdbc:mysql://localhost:3308/book_store
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    
server:
  port: 9090
